<?php 
return [
  [
    'name' => 'bismack',
    'image' => 'uploads/images/h3-product-img-1a-100x100.png',
    'description' => 'Una deliziosa pizza con base di mozzarella e prosciutto cotto, arricchita con funghi freschi e un tocco di origano per un sapore unico e irresistibile.',
    'price' => 30.00,
    'discount_percent' => 0,
    'available' => true,
  ],
  [
    'name' => 'fiori di zucca',
    'image' => 'uploads/images/h3-product-img-2a-150x150.png',
    'description' => 'Una raffinata pizza con fiori di zucca freschi, mozzarella e acciughe, il tutto su una base croccante e leggermente dorata.',
    'price' => 30.00,
    'discount_percent' => 10,
    'available' => true,
  ],
  [
    'name' => 'valdostana',
    'image' => 'uploads/images/h3-product-img-3a-150x150.png',
    'description' => 'Una pizza ricca e saporita con fontina, prosciutto crudo e uova, che richiama i sapori tipici della Valle d\'Aosta.',
    'price' => 55.00,
    'discount_percent' => 30,
    'available' => true,
  ],
  [
    'name' => 'pizza tartufata',
    'image' => 'uploads/images/h3-product-img-4a-150x150.png',
    'description' => 'Una pizza gourmet con crema di tartufo, mozzarella, funghi porcini e scaglie di parmigiano. Un\'esperienza culinaria di lusso.',
    'price' => 45.00,
    'discount_percent' => 5,
    'available' => true,
  ],
  [
    'name' => 'francescana',
    'image' => 'uploads/images/h3-product-img-5a-150x150.png',
    'description' => 'Una pizza semplice e gustosa con pomodoro, mozzarella, cipolle, salsiccia e una spruzzata di pepe nero.',
    'price' => 25.00,
    'discount_percent' => 0,
    'available' => true,
  ],
  [
    'name' => 'campagnola',
    'image' => 'uploads/images/h3-product-img-6a-100x100.png',
    'description' => 'Una pizza rustica con mozzarella, pomodorini, pancetta, e un tocco di rosmarino fresco per un sapore autentico e genuino.',
    'price' => 29.50,
    'discount_percent' => 0,
    'available' => false,
  ],
  [
    'name' => 'margherita',
    'image' => 'uploads/images/h3-product-img-7a-150x150.jpg',
    'description' => 'La classica pizza margherita con pomodoro, mozzarella e basilico fresco. Un\'icona della cucina italiana.',
    'price' => 20.00,
    'discount_percent' => 0,
    'available' => true,
  ],
  [
    'name' => 'diavola',
    'image' => 'uploads/images/h3-product-img-8a-150x150.jpg',
    'description' => 'Una pizza piccante con mozzarella, pomodoro e salame piccante. Perfetta per chi ama i sapori forti.',
    'price' => 28.00,
    'discount_percent' => 15,
    'available' => true,
  ],
  [
    'name' => 'quattro stagioni',
    'image' => 'uploads/images/h3-product-img-9a-150x150.jpg',
    'description' => 'Una pizza con quattro sezioni, ognuna con un diverso ingrediente: funghi, prosciutto, carciofi e olive.',
    'price' => 35.00,
    'discount_percent' => 5,
    'available' => true,
  ],
  [
    'name' => 'capricciosa',
    'image' => 'uploads/images/h3-product-img-10a-150x150.jpg',
    'description' => 'Una pizza ricca di sapori con mozzarella, pomodoro, funghi, prosciutto, carciofi e olive.',
    'price' => 33.00,
    'discount_percent' => 10,
    'available' => true,
  ],
  [
    'name' => 'ortolana',
    'image' => 'uploads/images/h3-product-img-11a-150x150.jpg',
    'description' => 'Una pizza vegetariana con mozzarella, pomodoro, zucchine, melanzane e peperoni. Sana e gustosa.',
    'price' => 32.00,
    'discount_percent' => 0,
    'available' => true,
  ],
  [
    'name' => 'mare e monti',
    'image' => 'uploads/images/h3-product-img-12a-150x150.jpg',
    'description' => 'Una pizza con un mix di frutti di mare e funghi, unendo il meglio della terra e del mare.',
    'price' => 38.00,
    'discount_percent' => 20,
    'available' => true,
  ],
  [
    'name' => 'boscaiola',
    'image' => 'uploads/images/h3-product-img-13a-150x150.jpg',
    'description' => 'Una pizza con salsiccia, funghi, mozzarella e pomodoro, dal sapore rustico e avvolgente.',
    'price' => 30.00,
    'discount_percent' => 10,
    'available' => true,
  ],
  [
    'name' => 'carbonara',
    'image' => 'uploads/images/h3-product-img-14a-150x150.jpg',
    'description' => 'Una pizza ispirata alla famosa pasta carbonara, con uova, pancetta, pecorino e pepe nero.',
    'price' => 34.00,
    'discount_percent' => 5,
    'available' => true,
  ],
  [
    'name' => 'napoletana',
    'image' => 'uploads/images/h3-product-img-15a-150x150.jpg',
    'description' => 'Una pizza tradizionale con pomodoro, mozzarella, acciughe e capperi. Un classico intramontabile.',
    'price' => 27.00,
    'discount_percent' => 0,
    'available' => true,
  ],
  [
    'name' => 'quattro formaggi',
    'image' => 'uploads/images/h3-product-img-16a-150x150.jpg',
    'description' => 'Una pizza cremosa con una combinazione di quattro formaggi: mozzarella, gorgonzola, fontina e parmigiano.',
    'price' => 31.00,
    'discount_percent' => 10,
    'available' => true,
  ],
  [
    'name' => 'bufalina',
    'image' => 'uploads/images/h3-product-img-17a-150x150.jpg',
    'description' => 'Una pizza con mozzarella di bufala fresca, pomodorini e basilico, per un sapore fresco e autentico.',
    'price' => 36.00,
    'discount_percent' => 15,
    'available' => true,
  ],
  [
    'name' => 'salmone',
    'image' => 'uploads/images/h3-product-img-18a-150x150.jpg',
    'description' => 'Una pizza gourmet con salmone affumicato, rucola, mozzarella e un tocco di limone.',
    'price' => 40.00,
    'discount_percent' => 20,
    'available' => true,
  ],
  [
    'name' => 'funghi e tartufo',
    'image' => 'uploads/images/h3-product-img-19a-150x150.jpg',
    'description' => 'Una pizza sofisticata con funghi porcini, crema di tartufo e mozzarella. Un piacere per il palato.',
    'price' => 42.00,
    'discount_percent' => 25,
    'available' => true,
  ],
  [
    'name' => 'greca',
    'image' => 'uploads/images/h3-product-img-20a-150x150.jpg',
    'description' => 'Una pizza fresca e leggera con feta, olive nere, pomodorini e cipolle rosse. Un tocco mediterraneo.',
    'price' => 29.00,
    'discount_percent' => 0,
    'available' => true,
  ],
  [
    'name' => 'calabrese',
    'image' => 'uploads/images/h3-product-img-21a-150x150.jpg',
    'description' => 'Una pizza piccante con nduja calabrese, mozzarella e pomodoro. Ideale per chi ama i sapori intensi.',
    'price' => 33.00,
    'discount_percent' => 10,
    'available' => true,
  ],
  [
    'name' => 'patate e rosmarino',
    'image' => 'uploads/images/h3-product-img-22a-150x150.jpg',
    'description' => 'Una pizza semplice ma gustosa con patate sottili, mozzarella e rosmarino fresco.',
    'price' => 28.00,
    'discount_percent' => 0,
    'available' => true,
  ],
  [
    'name' => 'zucca e speck',
    'image' => 'uploads/images/h3-product-img-23a-150x150.jpg',
    'description' => 'Una pizza autunnale con crema di zucca, mozzarella e speck croccante. Un mix di sapori dolci e salati.',
    'price' => 34.00,
    'discount_percent' => 5,
    'available' => true,
  ],
  [
    'name' => 'gorgonzola e noci',
    'image' => 'uploads/images/h3-product-img-24a-150x150.jpg',
    'description' => 'Una pizza cremosa con gorgonzola dolce, noci croccanti e un filo di miele. Un sapore unico e delicato.',
    'price' => 37.00,
    'discount_percent' => 10,
    'available' => true,
  ],
  [
    'name' => 'salsiccia e friarielli',
    'image' => 'uploads/images/h3-product-img-25a-150x150.jpg',
    'description' => 'Una pizza tipica napoletana con salsiccia, friarielli (cime di rapa) e mozzarella. Ricca e saporita.',
    'price' => 32.00,
    'discount_percent' => 5,
    'available' => true,
  ],
  [
    'name' => 'pollo e peperoni',
    'image' => 'uploads/images/h3-product-img-26a-150x150.jpg',
    'description' => 'Una pizza con straccetti di pollo, peperoni grigliati e mozzarella. Un mix di sapori succulenti.',
    'price' => 29.00,
    'discount_percent' => 0,
    'available' => true,
  ],
  [
    'name' => 'melanzane e ricotta',
    'image' => 'uploads/images/h3-product-img-27a-150x150.jpg',
    'description' => 'Una pizza vegetariana con melanzane grigliate, ricotta fresca e pomodorini. Leggera e gustosa.',
    'price' => 31.00,
    'discount_percent' => 0,
    'available' => true,
  ],
  [
    'name' => 'prosciutto e funghi',
    'image' => 'uploads/images/h3-product-img-28a-150x150.jpg',
    'description' => 'Una pizza classica con prosciutto cotto, funghi freschi, mozzarella e pomodoro. Sempre un\'ottima scelta.',
    'price' => 28.00,
    'discount_percent' => 0,
    'available' => true,
  ],
  [
    'name' => 'tonno e cipolla',
    'image' => 'uploads/images/h3-product-img-29a-150x150.jpg',
    'description' => 'Una pizza saporita con tonno, cipolla rossa, mozzarella e pomodoro. Un classico mediterraneo.',
    'price' => 30.00,
    'discount_percent' => 10,
    'available' => true,
  ],
  [
    'name' => 'zola e speck',
    'image' => 'uploads/images/h3-product-img-30a-150x150.jpg',
    'description' => 'Una pizza dal gusto deciso con gorgonzola piccante e speck croccante, su una base di mozzarella.',
    'price' => 35.00,
    'discount_percent' => 15,
    'available' => true,
  ],
];

?>